// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqd2LCCA__p9o2afDyoJ3lR4b8kye9z3g',
    appId: '1:584362757991:web:4096ff5fc1c8bb5b0929c2',
    messagingSenderId: '584362757991',
    projectId: 'intern-tracker-8bb5a',
    authDomain: 'intern-tracker-8bb5a.firebaseapp.com',
    databaseURL: 'https://intern-tracker-8bb5a-default-rtdb.firebaseio.com',
    storageBucket: 'intern-tracker-8bb5a.firebasestorage.app',
    measurementId: 'G-3FT98F0H6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVchMWuqLokzsS3tLhwbePnXSQ032QyCc',
    appId: '1:584362757991:android:e151d52d695ccdda0929c2',
    messagingSenderId: '584362757991',
    projectId: 'intern-tracker-8bb5a',
    databaseURL: 'https://intern-tracker-8bb5a-default-rtdb.firebaseio.com',
    storageBucket: 'intern-tracker-8bb5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHeWas6_qXD4HMuOSwzxTXU0txPodqNNI',
    appId: '1:584362757991:ios:776b4e72c5b2dbcc0929c2',
    messagingSenderId: '584362757991',
    projectId: 'intern-tracker-8bb5a',
    databaseURL: 'https://intern-tracker-8bb5a-default-rtdb.firebaseio.com',
    storageBucket: 'intern-tracker-8bb5a.firebasestorage.app',
    androidClientId: '584362757991-e22g7vef7lu7mggmfjbgamq4n972umeq.apps.googleusercontent.com',
    iosClientId: '584362757991-u99h2bnob1r3ntokde2mohbcpvvh8q1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.interntrackerAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHeWas6_qXD4HMuOSwzxTXU0txPodqNNI',
    appId: '1:584362757991:ios:776b4e72c5b2dbcc0929c2',
    messagingSenderId: '584362757991',
    projectId: 'intern-tracker-8bb5a',
    databaseURL: 'https://intern-tracker-8bb5a-default-rtdb.firebaseio.com',
    storageBucket: 'intern-tracker-8bb5a.firebasestorage.app',
    androidClientId: '584362757991-e22g7vef7lu7mggmfjbgamq4n972umeq.apps.googleusercontent.com',
    iosClientId: '584362757991-u99h2bnob1r3ntokde2mohbcpvvh8q1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.interntrackerAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqd2LCCA__p9o2afDyoJ3lR4b8kye9z3g',
    appId: '1:584362757991:web:bb77cb99e3e52c110929c2',
    messagingSenderId: '584362757991',
    projectId: 'intern-tracker-8bb5a',
    authDomain: 'intern-tracker-8bb5a.firebaseapp.com',
    databaseURL: 'https://intern-tracker-8bb5a-default-rtdb.firebaseio.com',
    storageBucket: 'intern-tracker-8bb5a.firebasestorage.app',
    measurementId: 'G-ESZ9RPJS8D',
  );
}
